/*
 *  Copyright 2013 Paul Miller. All rights reserved.
 *
 */

#pragma once

#define STRINGIFY(...) STRINGIFY_AUX(__VA_ARGS__)
#define STRINGIFY_AUX(...) #__VA_ARGS__

// GLOBAL ENUMS USED IN MORE THAN 1 MODULE - ALPHABETICAL:

enum TX2DCURVETYPE {
    TX2DCURVETYPE_AUTOCURVE,
    TX2DCURVETYPE_STRAIGHT,
    TX2DCURVETYPE_BEZIER1,
    TX2DCURVETYPE_BEZIER2,
    TX2DCURVETYPE_BEZIER3
};

enum TX2DSHAPETYPE {
    TX2DSHAPETYPE_CIRCLE,
    TX2DSHAPETYPE_ELLIPSE,
    TX2DSHAPETYPE_SQUARE,
    TX2DSHAPETYPE_RECTANGLE,
    TX2DSHAPETYPE_ROUNDRECTANGLE,
    TX2DSHAPETYPE_STAR,
    TX2DSHAPETYPE_ISOSCELES_TRIANGLE,
    TX2DSHAPETYPE_RIGHT_TRIANGLE,
    TX2DSHAPETYPE_DIAMOND,
    TX2DSHAPETYPE_CRESCENT,
    TX2DSHAPETYPE_RING,
};


// FOR OLDER SYSTEMS - NOW REPLACED BY TXSHAPE3D ============
enum TX3DSHAPETYPE {
    TX3DSHAPETYPE_SPHERE,
    TX3DSHAPETYPE_ICOSPHERE,
    TX3DSHAPETYPE_BOX,
    TX3DSHAPETYPE_PLANE,
    TX3DSHAPETYPE_CYLINDER,
    TX3DSHAPETYPE_ROUNDEDCYLINDER,
    TX3DSHAPETYPE_UNCAPPEDCYLINDER,
    TX3DSHAPETYPE_CONE,
    TX3DSHAPETYPE_ROUNDEDCONE,
    TX3DSHAPETYPE_UNCAPPEDCONE,
    // TX3DSHAPETYPE_ICOSAHEDRON,  // not working yet
};
enum TX3DSHAPEDISTORTWAVETYPE {
    TX3DSHAPEDISTORTWAVETYPE_SINE,
    TX3DSHAPEDISTORTWAVETYPE_COSINE,
    TX3DSHAPEDISTORTWAVETYPE_SQUARE,
    TX3DSHAPEDISTORTWAVETYPE_RAMPUP,
    TX3DSHAPEDISTORTWAVETYPE_RAMPDOWN,
    TX3DSHAPEDISTORTWAVETYPE_TRIANGLE,
    TX3DSHAPEDISTORTWAVETYPE_CUSTOMCURVE,
    TX3DSHAPEDISTORTWAVETYPE_CUSTOMCURVE_MIRRORED,
};
enum TX3DSHAPEDISTORTORDER {
    TX3DSHAPEDISTORTORDER_WAVEPERLINTWISTBEND,
    TX3DSHAPEDISTORTORDER_PERLINWAVETWISTBEND,
    TX3DSHAPEDISTORTORDER_TWISTPERLINWAVEBEND,
    TX3DSHAPEDISTORTORDER_BENDPERLINTWISTWAVE,
    TX3DSHAPEDISTORTORDER_WAVETWISTPERLINBEND,
    TX3DSHAPEDISTORTORDER_PERLINTWISTWAVEBEND,
    TX3DSHAPEDISTORTORDER_TWISTWAVEPERLINBEND,
    TX3DSHAPEDISTORTORDER_BENDTWISTPERLINWAVE,
    TX3DSHAPEDISTORTORDER_WAVEBENDTWISTPERLIN,
    TX3DSHAPEDISTORTORDER_PERLINBENDTWISTWAVE,
    TX3DSHAPEDISTORTORDER_TWISTBENDWAVEPERLIN,
    TX3DSHAPEDISTORTORDER_BENDWAVETWISTPERLIN,
    TX3DSHAPEDISTORTORDER_WAVEPERLINBENDTWIST,
    TX3DSHAPEDISTORTORDER_PERLINWAVEBENDTWIST,
    TX3DSHAPEDISTORTORDER_TWISTPERLINBENDWAVE,
    TX3DSHAPEDISTORTORDER_BENDPERLINWAVETWIST,
    TX3DSHAPEDISTORTORDER_WAVETWISTBENDPERLIN,
    TX3DSHAPEDISTORTORDER_PERLINTWISTBENDWAVE,
    TX3DSHAPEDISTORTORDER_TWISTWAVEBENDPERLIN,
    TX3DSHAPEDISTORTORDER_BENDTWISTWAVEPERLIN,
    TX3DSHAPEDISTORTORDER_WAVEBENDPERLINTWIST,
    TX3DSHAPEDISTORTORDER_PERLINBENDWAVETWIST,
    TX3DSHAPEDISTORTORDER_TWISTBENDPERLINWAVE,
    TX3DSHAPEDISTORTORDER_BENDWAVEPERLINTWIST,
    TX3DSHAPEDISTORTORDER_TOTAL
};
// END OF OLDER TX3DSHAPE SECTION ============

enum TXSHAPE3DTYPE {
    TXSHAPE3DTYPE_SPHERE,
    TXSHAPE3DTYPE_ICOSPHERE,
    TXSHAPE3DTYPE_BOX,
    TXSHAPE3DTYPE_PLANE,
    TXSHAPE3DTYPE_CYLINDER,
    TXSHAPE3DTYPE_ROUNDEDCYLINDER,
    TXSHAPE3DTYPE_UNCAPPEDCYLINDER,
    TXSHAPE3DTYPE_CONE,
    TXSHAPE3DTYPE_ROUNDEDCONE,
    TXSHAPE3DTYPE_UNCAPPEDCONE,
    // TXSHAPE3DTYPE_ICOSAHEDRON,  // not working yet
};
enum TXCAMERAORIENTATIONMODE {
    TXCAMERAORIENTATIONMODE_USEROTATIONXYZ,
    TXCAMERAORIENTATIONMODE_TILTPANROLL,
    TXCAMERAORIENTATIONMODE_TRIGTILTPANROLL,
    TXCAMERAORIENTATIONMODE_LOOKATPOINT,
    TXCAMERAORIENTATIONMODE_TOTAL
};

enum TXCAMERAPOSITIONMODE {
    TXCAMERAPOSITIONMODE_USEPOSITIONXYZ,
    TXCAMERAPOSITIONMODE_TRUCKBOOMDOLLY,
    TXCAMERAPOSITIONMODE_TRIGTRUCKBOOMDOLLY,
    TXCAMERAPOSITIONMODE_ORBIT,
    TXCAMERAPOSITIONMODE_TOTAL};

enum TXCOLORRGBHSLCHANNELMODE {
    TXCOLORRGBHSLCHANNELMODE_RGB,
    TXCOLORRGBHSLCHANNELMODE_RED,
    TXCOLORRGBHSLCHANNELMODE_GREEN,
    TXCOLORRGBHSLCHANNELMODE_BLUE,
    TXCOLORRGBHSLCHANNELMODE_REDGREEN,
    TXCOLORRGBHSLCHANNELMODE_REDBLUE,
    TXCOLORRGBHSLCHANNELMODE_GREENBLUE,
    TXCOLORRGBHSLCHANNELMODE_HSL,
    TXCOLORRGBHSLCHANNELMODE_HUE,
    TXCOLORRGBHSLCHANNELMODE_SATURATION,
    TXCOLORRGBHSLCHANNELMODE_LUMINOSITY,
    TXCOLORRGBHSLCHANNELMODE_HUESATURATION,
    TXCOLORRGBHSLCHANNELMODE_HUELUMINOSITY,
    TXCOLORRGBHSLCHANNELMODE_SATURATIONLUMINOSITY,
    TXCOLORRGBHSLCHANNELMODE_TOTAL
};

enum TXCOLORRGBHSLCHANNEL {
    TXCOLORRGBHSLCHANNEL_RED,
    TXCOLORRGBHSLCHANNEL_GREEN,
    TXCOLORRGBHSLCHANNEL_BLUE,
    TXCOLORRGBHSLCHANNEL_HUE,
    TXCOLORRGBHSLCHANNEL_SATURATION,
    TXCOLORRGBHSLCHANNEL_LUMINOSITY,
    TXCOLORRGBHSLCHANNEL_TOTAL
};

enum TXCOLORRGBCHANNELORDER {
    TXCOLORRGBCHANNELORDER_RGB,
    TXCOLORRGBCHANNELORDER_RBG,
    TXCOLORRGBCHANNELORDER_GBR,
    TXCOLORRGBCHANNELORDER_GRB,
    TXCOLORRGBCHANNELORDER_BRG,
    TXCOLORRGBCHANNELORDER_BGR,
    TXCOLORRGBCHANNELORDER_TOTAL,
};

enum TXFRACTALBRANCHRULE {
    TXFRACTALBRANCHRULE_ALWAYSBRANCH,
    TXFRACTALBRANCHRULE_BRANCHIFGREATER,
    TXFRACTALBRANCHRULE_BRANCHIFLESS,
    TXFRACTALBRANCHRULE_BRANCHIFEQUAL,
    TXFRACTALBRANCHRULE_BRANCHIFNOTEQUAL
};

enum IMAGEFXWIDTHHEIGHTRULE {
    IMAGEFXWIDTHHEIGHTRULE_SCREENWIDTHHEIGHT, // 0
    IMAGEFXWIDTHHEIGHTRULE_MAXSCREENWIDTHHEIGHT, // 1
    IMAGEFXWIDTHHEIGHTRULE_MINSCREENWIDTHHEIGHT, // 2
    IMAGEFXWIDTHHEIGHTRULE_SQUARESCREENWIDTH, // 3
    IMAGEFXWIDTHHEIGHTRULE_SQUARESCREENHEIGHT, // 4
    IMAGEFXWIDTHHEIGHTRULE_CUSTOMSIZE, // 5
    IMAGEFXWIDTHHEIGHTRULE_SOURCEIMAGESIZE, // 6
    IMAGEFXWIDTHHEIGHTRULE_640_480, // 7
    IMAGEFXWIDTHHEIGHTRULE_640_360, // 8
    IMAGEFXWIDTHHEIGHTRULE_1280_720, // 9
    IMAGEFXWIDTHHEIGHTRULE_1920_1080, // 10
    IMAGEFXWIDTHHEIGHTRULE_2560_1440, // 11
    IMAGEFXWIDTHHEIGHTRULE_3840_2160, // 12
};

// scale modes: "scale to fit", "scale to fill", "stretch to fill"
enum TXIMAGESCALEMODE {
    TXIMAGESCALEMODE_SCALETOFIT,
    TXIMAGESCALEMODE_SCALETOFILL,
    TXIMAGESCALEMODE_STRETCHTOFILL};

enum TXLIGHTTYPE {
    TXLIGHTTYPE_POINT,
    TXLIGHTTYPE_DIRECTIONAL,
    TXLIGHTTYPE_SPOT,
    TXLIGHTTYPE_TOTAL};

enum TXMASKTYPE {
    TXMASKTYPE_NOMASK,
    TXMASKTYPE_USEMASKIMAGE,
    TXMASKTYPE_FEATHEREDSQUARE,
    TXMASKTYPE_CIRCLE,
    TXMASKTYPE_FEATHEREDCIRCLE,
    TXMASKTYPE_BLURREDCIRCLE,
    TXMASKTYPE_RING,
    TXMASKTYPE_FEATHEREDRING,
    TXMASKTYPE_DIAMOND,
    TXMASKTYPE_FEATHEREDDIAMOND, };

enum TXPOINTSMORPHTYPE {
    TXPOINTSMORPHTYPE_NOMORPH,
    TXPOINTSMORPHTYPE_SOLOMORPHPRESETA,
    TXPOINTSMORPHTYPE_SOLOMORPHPRESETB,
    TXPOINTSMORPHTYPE_SOLOMORPHPRESETC,
    TXPOINTSMORPHTYPE_SOLOMORPHPRESETD,
    TXPOINTSMORPHTYPE_SOLOMORPHPRESETE,
    TXPOINTSMORPHTYPE_LINEAR2SETS,
    TXPOINTSMORPHTYPE_LINEAR3SETS,
    TXPOINTSMORPHTYPE_LINEAR4SETS,
    TXPOINTSMORPHTYPE_LINEAR5SETS,
    TXPOINTSMORPHTYPE_2D4SETS,
    TXPOINTSMORPHTYPE_2D5SETS,
    TXPOINTSMORPHTYPE_TOTAL,
};

enum TXSHAPE3DDISTORTORDER {
    TXSHAPE3DDISTORTORDER_WAVETWISTBEND,
    TXSHAPE3DDISTORTORDER_WAVEBENDTWIST,
    TXSHAPE3DDISTORTORDER_TWISTBENDWAVE,
    TXSHAPE3DDISTORTORDER_TWISTWAVEBEND,
    TXSHAPE3DDISTORTORDER_BENDTWISTWAVE,
    TXSHAPE3DDISTORTORDER_BENDWAVETWIST,
    TXSHAPE3DDISTORTORDER_TOTAL
};
enum TXSHAPE3DDISTORTWAVEFORM {
    TXSHAPE3DDISTORTWAVEFORM_SINE,
    TXSHAPE3DDISTORTWAVEFORM_COSINE,
    TXSHAPE3DDISTORTWAVEFORM_SQUARE,
    TXSHAPE3DDISTORTWAVEFORM_RAMPUP,
    TXSHAPE3DDISTORTWAVEFORM_RAMPDOWN,
    TXSHAPE3DDISTORTWAVEFORM_TRIANGLE,
    TXSHAPE3DDISTORTWAVEFORM_CUSTOMCURVE,
    TXSHAPE3DDISTORTWAVEFORM_CUSTOMCURVE_MIRRORED,
};
enum TXSHAPE3DDISTORTWAVE {
    TXSHAPE3DDISTORTWAVE_WAVE1,
    TXSHAPE3DDISTORTWAVE_WAVE2,
    TXSHAPE3DDISTORTWAVE_WAVE3,
    TXSHAPE3DDISTORTWAVE_WAVE4,
    TXSHAPE3DDISTORTWAVE_WAVE5,
    TXSHAPE3DDISTORTWAVE_PERLIN1,
    TXSHAPE3DDISTORTWAVE_PERLIN2,
    TXSHAPE3DDISTORTWAVE_PERLIN3,
    TXSHAPE3DDISTORTWAVE_TOTAL
};
enum TXSHAPE3DDISTORTAXIS {
    TXSHAPE3DDISTORTAXIS_POSXONY,
    TXSHAPE3DDISTORTAXIS_POSXONZ,
    TXSHAPE3DDISTORTAXIS_POSYONX,
    TXSHAPE3DDISTORTAXIS_POSYONZ,
    TXSHAPE3DDISTORTAXIS_POSZONX,
    TXSHAPE3DDISTORTAXIS_POSZONY,
    TXSHAPE3DDISTORTAXIS_POSYZRADIALONX,
    TXSHAPE3DDISTORTAXIS_POSXZRADIALONY,
    TXSHAPE3DDISTORTAXIS_POSXYRADIALONZ,
    TXSHAPE3DDISTORTAXIS_TOTAL
};
enum TXSHAPE3DDISTORTTYPE {
    TXSHAPE3DDISTORTTYPE_MULTIPLYALL,
    TXSHAPE3DDISTORTTYPE_MULTIPLYPOS,
    TXSHAPE3DDISTORTTYPE_MULTIPLYNEG,
    TXSHAPE3DDISTORTTYPE_ADDALL,
    TXSHAPE3DDISTORTTYPE_ADDPOSSUBTRACTNEG,
    TXSHAPE3DDISTORTTYPE_ADDPOS,
    TXSHAPE3DDISTORTTYPE_SUBTRACTNEG,
    TXSHAPE3DDISTORTTYPE_TOTAL
};

enum TXSMOOTHTYPE {
    TXSMOOTHTYPE_EXPONENTIAL,
    TXSMOOTHTYPE_LINEAR
};

enum TXTRANSFORMORDER {
    TXTRANSFORMORDER_SHIFTROTATESCALE,
    TXTRANSFORMORDER_SHIFTSCALEROTATE,
    TXTRANSFORMORDER_ROTATESCALESHIFT,
    TXTRANSFORMORDER_ROTATESHIFTSCALE,
    TXTRANSFORMORDER_SCALESHIFTROTATE,
    TXTRANSFORMORDER_SCALEROTATESHIFT,
    TXTRANSFORMORDER_TOTAL
};

